// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqjYpMi9_9xRuxfXAoreC-b2ABLlRAijQ',
    appId: '1:207429338995:web:8f68307b4e0a6ad521a706',
    messagingSenderId: '207429338995',
    projectId: 'evently-c16-71d7e',
    authDomain: 'evently-c16-71d7e.firebaseapp.com',
    storageBucket: 'evently-c16-71d7e.firebasestorage.app',
    measurementId: 'G-FHXF050L2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSGbqqFc34k8BVBZv-jg0yZQL65KWNDR4',
    appId: '1:207429338995:android:318c45ede5b7848d21a706',
    messagingSenderId: '207429338995',
    projectId: 'evently-c16-71d7e',
    storageBucket: 'evently-c16-71d7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt4cxoU_k2mp8jUxCqNSdKMGGHTGjM9fU',
    appId: '1:207429338995:ios:a3e3932b2171339f21a706',
    messagingSenderId: '207429338995',
    projectId: 'evently-c16-71d7e',
    storageBucket: 'evently-c16-71d7e.firebasestorage.app',
    androidClientId: '207429338995-u2jnfvs2t34kj2bs9p2mjb5vc14naenq.apps.googleusercontent.com',
    iosClientId: '207429338995-b4omvr5f7lfrqeta31t9nbfh5lhd93iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt4cxoU_k2mp8jUxCqNSdKMGGHTGjM9fU',
    appId: '1:207429338995:ios:a3e3932b2171339f21a706',
    messagingSenderId: '207429338995',
    projectId: 'evently-c16-71d7e',
    storageBucket: 'evently-c16-71d7e.firebasestorage.app',
    androidClientId: '207429338995-u2jnfvs2t34kj2bs9p2mjb5vc14naenq.apps.googleusercontent.com',
    iosClientId: '207429338995-b4omvr5f7lfrqeta31t9nbfh5lhd93iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqjYpMi9_9xRuxfXAoreC-b2ABLlRAijQ',
    appId: '1:207429338995:web:fa4dff273597171521a706',
    messagingSenderId: '207429338995',
    projectId: 'evently-c16-71d7e',
    authDomain: 'evently-c16-71d7e.firebaseapp.com',
    storageBucket: 'evently-c16-71d7e.firebasestorage.app',
    measurementId: 'G-67977Z6NGM',
  );
}
